### ISSUE TITLE
Feature Request: deferral dates

### ISSUE THREAD

**Issue by vc5047** [macadmins/sofa#68]
First off, I love this project. Great work! Thank you!

A lot of admins implement times deferrals via config profiles, to delay the availability of updates to end users, so that they (the admins) can regression test.

It would be really cool if Sofa could calculate availability dates and add these to it's data set. This could either be a predefined default (like 30d, 45d, 60d, 90d) or even a customizable feature for self-hosting.

The way I imagine this would like like this:

in the JSON:
```json
                {
                    "UpdateName": "macOS Sonoma 14.4.1",
                    "ProductVersion": "14.4.1",
                    "ReleaseDate": "2024-03-25T00:00:00Z",
                    "SecurityInfo": "https://support.apple.com/kb/HT214096",
                    "CVEs": {
                        "CVE-2024-1580": false
                    },
                    "ActivelyExploitedCVEs": [],
                    "UniqueCVEsCount": 1,
                    "DaysSincePreviousRelease": 18,
                    "Deferral30": "2024-04-24T00:00:00Z",
                    "Deferral45": "2024-05-09T00:00:00Z",
                    "Deferral60": "2024-05-24T00:00:00Z",
                    "Deferral90": "2024-06-23T00:00:00Z",
                },
```

In the GUI similar items could be added to the individual "macOS Security Updates Overview" items.

**Comment by arubdesu** [comment]
Hey @vc5047 I understand the request and would tend to agree with 90 days as that's the maximum window, it's just we have no idea how many environments primarily use which delay and kind of want to stuff the feed with so much other info this might not be the best use of 'real estate' as it were? We currently just say how many days (I wonder if the postdate key I see in the feed sometimes is the most accurate signal of exact release time? but) since each release and then you could calculate it locally...
Would you mind sharing your use case, btw?

**Comment by erikng** [comment]
I think it would be better to write a simple tool to assess the sofa feed yourself and compute these days. It would be pretty simple to do in bash/zsh/python/swift/etc.

I bring this up because we are dealing with https://github.com/macadmins/sofa/issues/97 and the more we manipulate dates, the more we would run into this issue. Going to close this, focus on issue 97 and people can extend for their use cases as needed within their own domain.
